dataset:
  _target_: mixmate.datasets.FashionMNIST
  data_path: ${hydra:runtime.cwd}/data/
  download: True
  classes_only: '012'
  val_frac: 0.1
  train_batch_size: 16
  valid_batch_size: 16
mixmate:
  # autoencoder_config:
  #   _target_: mixmate.encoders.CRsAE
  #   dictionary_dim: 5
  #   num_iters: 15
  #   num_conv: 32
  #   stride: 1
  #   L: 100
  #   lam: 0.1
  #   twosided: True
  #   device: cuda
  autoencoder_config:
    _target_: mixmate.encoders.GroupSparseAE
    num_layers: 15
    num_groups: 40
    group_size: 1
    input_size: 784
    sparse_penalty: 0.75
    group_sparse_penalty: 0.0
    step: 0.04
    two_sided: True
  num_components: 3
  beta: 0
  lr: 5e-4
trainer:
  gpus: 1
  max_epochs: 20
  check_val_every_n_epoch: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: -1
  log_every_n_steps: 1
num_prelabeled: 40
