dataset:
  _target_: mixmate.datasets.SemiSupervisedMNIST
  data_path: ${hydra:runtime.cwd}/data/
  download: True
  classes_only: ';01'
  valid_size: 10000
  labeled_per_class: 100
  labeled_batch_size: 32
  unlabeled_batch_size: 128
  valid_batch_size: 128
mixmate:
  num_layers: 15
  input_size: 784
  hidden_size: 32
  sparse_penalty: 0.75
  step_size: 0.04
  num_components: 10
  beta: 0
  alpha: 1e2
  lr: 5e-4
trainer:
  gpus: 1
  max_epochs: 80
  check_val_every_n_epoch: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: -1
  log_every_n_steps: 1
